### PR TITLE
Lower minSdk to 15

### PR DESCRIPTION
**Pull request by cbruegg**
Here's a cleaned up version of PR #3.

### CODE REVIEW

**Comment by cbruegg** [comment]
Looks like your CI server is running an outdated JDK (1.7).

**Comment by pavlospt** [comment]
Hello, how did you conclude on this?

**Comment by cbruegg** [comment]
See the failed check on circle CI:

```
* What went wrong:
A problem occurred configuring project ':app'.
> Buildtools 24.0.2 requires Java 1.8 or above.  Current JDK version is 1.7.
```

**Comment by pavlospt** [comment]
So you updated the BuildTools to run with 24.0.2 ?

**Comment by cbruegg** [comment]
Yes, I thought it would be a good idea to update as many dependencies as possible.

**Comment by pavlospt** [comment]
I am not sure if I can upgrade the JDK version on CircleCI. Will try to search it though!

**Comment by pavlospt** [comment]
Yes I have already added it to master.

**Comment by pavlospt** [comment]
Ok it is fixed. You can rebase the Pull Request so that it will respect circle.yml of master branch.

**Comment by cbruegg** [comment]
Done :+1:

**Comment by pavlospt** [comment]
Great, thank you for your work. Will try to merge and upload on the following weekend!

**Comment by pavlospt** [comment]
Unfortunately there is a reason why I updated the misdkVersion to 19. Can you please update it to 19 and recommit?

**Comment by cbruegg** [comment]
What is the reason? I couldn't find a method it calls that is not supported
by SDK 15.

Pavlos-Petros Tournaris <notifications@github.com> schrieb am Sa., 17. Sep.
2016, 00:36:

**Pull request merged**
