### PR TITLE
Fix requestCode on BillingProcessor

### PR DESCRIPTION
**Pull request by FireZenk**

### CODE REVIEW

**Comment by pavlospt** [comment]
Thank you for your PR. Can you please add a .gitignore file on your repo so that all these files generated by Intellij, don't get commited?

**Comment by FireZenk** [comment]
Done

**Comment by pavlospt** [comment]
Are you using Intellij or Android Studio to build the project?

**Comment by FireZenk** [comment]
Android Studio

**Comment by FireZenk** [comment]
Im opening a new pull-request

**Pull request closed without merging**
